config/routes.rb
Rails.application.routes.draw do
  mount RailsEventStore::Browser => '/res' if Rails.env.development?

  resources :sales
end

app/models/agreement.rb
class Agreement < ApplicationRecord
  belongs_to :owner, polymorphic: true
  belongs_to :company
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :platform
end

app/models/company_sales_person.rb
class CompanySalesPerson < ApplicationRecord
  belongs_to :company
  belongs_to :sales_person
end

app/models/invoice_printed.rb
#frozen_string_literal: true
class InvoicePrinted < RailsEventStore::Event
end

app/models/platform.rb
class Platform < ApplicationRecord
  
end

app/models/sales_person.rb
class SalesPerson < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  def new
    @sale = Sales::Sale.new
    render :new
  end

  def create
    sale = Sales::Sale.create(
      quantity: params[:sales_sale][:quantity],
      product_id: params[:product_id][:product_id],
      sales_person_id: SalesPerson.find_by(name: "MyGuy").id, #mock of current user etc
      company_id: Products::Product.find(params[:product_id][:product_id]).company.id
    )
    Rails.configuration.command_bus.(
      Sales::MakeSale.new(
        sale_id: sale.id,
        quantity: sale.quantity,
        product_id: sale.product_id
      )
    )
    head :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DddApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/new.html.erb
<%= form_with model: @sale, url: sales_path, class: "nifty_form" do |f| %>
  <%= f.number_field :quantity, placeholder: "Products sold" %>
  <%= collection_select(:product_id, :product_id, Products::Product.all, :id, :name) %>
  <%= f.submit "Submit sale" %>
<% end %>